### ISSUE TITLE
型ファイルの作成

### ISSUE THREAD

**Issue by hand-dot** [nestengineering/template-editor#23]

**Comment by hand-dot** [comment]
これは集まった時にやった方がガブリが型のオプションとか詳しそうなので早そう

**Comment by azure06** [comment]
これは多分すぐクローズにすることはできないね。

**Comment by hand-dot** [comment]
そうかな？readmeに必要なメソッドは書き出していると思うけど、それ以外には型にするつもりはない

**Comment by hand-dot** [comment]
多分おれが見えていない部分のことを言っているんだとおもうけど、また教えてほしい

**Comment by azure06** [comment]
一発でうまくいくのかな？

**Comment by hand-dot** [comment]
とりあえず作成したらクローズするつもり！
