### ISSUE TITLE
TextFieldにtypeが設定されていない

### ISSUE THREAD

**Issue by hand-dot** [nestengineering/template-editor#28]
多分下記の場所でデバックしてもらったらtypeが設定されていないと思う。

https://github.com/nestengineering/template-editor/blob/7d94097e3bd59adbca5528255b35610a9af497de/unity/Assets/Scripts/Canvas/CanvasPorts.cs#L29

少なくとも、fieldを追加した後に下記の場所でconsole.logしたfieldsのデータにはtypeプロパティ自体なかった
https://github.com/nestengineering/template-editor/blob/a2423dd1df37bb7125f48264b93fe72cd2c48f1b/src/index.tsx#L44

**Comment by azure06** [comment]
これjson変換を実施するときに送るバグだね。アプローチ変えてみます

**Comment by hand-dot** [comment]
ありがとう！
