### ISSUE TITLE
unityInstance.SendMessage('Canvas', 'FieldChange', JSON.stringify(field));が動かない

### ISSUE THREAD

**Issue by hand-dot** [nestengineering/template-editor#33]
https://github.com/nestengineering/template-editor/blob/1685e3c1a5716a5db5d2c8c0160c9f53d5c21912/src/index.tsx#L81

上記のコードが動いていないっぽい

@azure06 
uniy側で未実装なのか、バグなのかまだわからないのでもし知っていることがあれば教えてください

**Comment by azure06** [comment]
まじか、、、バグですね。確認します。

**Comment by hand-dot** [comment]
@azure06 
たとえば、fieldnameを書き込んだときにinputが反映されなくて、
コンソール見てみたら
```
Field not found
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

のエラーが出ていました。。。

**Comment by azure06** [comment]
ありがとう！今直します

**Comment by hand-dot** [comment]
ありがとうございます！
